databases:
  - name: baystars_DB
    databaseName: baystars_db
    user: baystars
    region: singapore

services:
  - type: web
    name: baystars
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: baystars_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

